---
title: "Learn Package Complex Heatmap"
author: "Kuei Yueh Ko"
date: "2017年4月26日"
output: html_document
---

```{r}
library(ComplexHeatmap)
```

# Recommend reference
A short tutorial for decent heat maps in R
http://sebastianraschka.com/Articles/heatmaps_in_r.html

Static and Interactive Heatmap in R - Unsupervised Machine Learning
http://www.sthda.com/english/wiki/static-and-interactive-heatmap-in-r-unsupervised-machine-learning

ComplexHeatmap
https://bioconductor.org/packages/release/bioc/html/ComplexHeatmap.html

# test some function

**Making A Single Heatmap**
https://bioconductor.org/packages/release/bioc/vignettes/ComplexHeatmap/inst/doc/s2.single_heatmap.html
```{r}
# First let's load packages and generate a random matrix:
library(ComplexHeatmap)
library(circlize)

set.seed(123)

mat = cbind(rbind(matrix(rnorm(16, -1), 4), matrix(rnorm(32, 1), 8)),
            rbind(matrix(rnorm(24, 1), 4), matrix(rnorm(48, -1), 8)))

# permute the rows and columns
mat = mat[sample(nrow(mat), nrow(mat)), sample(ncol(mat), ncol(mat))]

rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

# Plot the heatmap with default settings. 
# The default style of the heatmap is quite 
# the same as those generated by other similar 
# heatmap functions.
Heatmap(mat)

# Colors
# Currently colorRamp2() linearly interpolates colors in 
# every interval through LAB color space.
mat2 = mat
mat2[1, 1] = 100000
Heatmap(mat2, col = colorRamp2(c(-3, 0, 3), c("green", "white", "red")), 
    cluster_rows = FALSE, cluster_columns = FALSE)
```

### Heatmap Annotations
https://bioconductor.org/packages/release/bioc/vignettes/ComplexHeatmap/inst/doc/s4.heatmap_annotation.html

```{r}
library(ComplexHeatmap)
library(circlize)

df = data.frame(type = c(rep("a", 5), rep("b", 5)))
ha = HeatmapAnnotation(df = df)
ha
```

```{r}
draw(ha, 1:10)
```

```{r}
ha = HeatmapAnnotation(df = df, col = list(type = c("a" =  "red", "b" = "blue")))
ha

draw(ha, 1:10)
```

```{r}
ha = HeatmapAnnotation(df = data.frame(age = sample(1:20, 10)),
    col = list(age = colorRamp2(c(0, 20), c("white", "red"))))
ha

draw(ha, 1:10)
```

```{r}
ha1 = HeatmapAnnotation(df = df,
    col = list(type = c("a" = "red", "b" = "blue"),
               age = colorRamp2(c(0, 20), c("white", "red")))
)
ha2 = HeatmapAnnotation(df = data.frame(age = sample(1:20, 10)),
    col = list(age = colorRamp2(c(0, 20), c("white", "red"))))

set.seed(123)
mat = matrix(rnorm(80, 2), 8, 10)
mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

Heatmap(mat, top_annotation = ha1, bottom_annotation = ha2)
```

```{r}
df <- data.frame(
    age = 0:10
)
ha1 = HeatmapAnnotation(
    df=df, annotation_height = unit(10, "mm"),
    col = list(age = colorRamp2(c(0, 10), c("white", "red"))))
draw(ha1, 0:10)

ha2 = HeatmapAnnotation(
    points = anno_points(df$age))
draw(ha2, 1:10)

ha2 = HeatmapAnnotation(
    points = anno_points(df$age))
draw(ha2, 1:10)


Heatmap(mat, 
        top_annotation=ha1, 
        bottom_annotation = ha2,
        bottom_annotation_height = unit(2, "cm"))
```

