---
title: "StatLearn HW02"
author: "Kuei Yueh Ko"
date: "2017/3/28Ѵ"
output: html_document
---

# Set Environment
```{r, warning=FALSE}
#install.packages("glmnet")
library(glmnet)

# set working directory
workdir <- "C:\\Users\\clint\\Documents\\GitHub\\BlogDataAnalysis"
setwd(workdir)
#dir()

filePathData <- file.path(
    workdir,
    "Data",
    "2017_CourseNTU_StatLearn")
```

read in data
```{r}
load(file.path(filePathData, "rtb1_train.rdata"))
tmp <- rtb1_train
head(tmp)
```

```{r}
rtb1_train <- tmp[1:300,]

head(rtb1_train[,c("user_tags", "paying_price")])
tail(rtb1_train[,c("user_tags", "paying_price")])

#utagsvec   <- rtb1_train$user_tags
#y <- rtb1_train$paying_price
```

```{r}
reg_tvalue <- function(y, x) {
    y = matrix(y, ncol=1)
    xmat = matrix(1, ncol=2, nrow=length(y))
    xmat[,2] = x
    bhead  = solve(t(xmat) %*% xmat, t(xmat) %*% y)
    yhead  = xmat %*% bhead
    e1     = y - yhead
    var1   = sum(e1 * e1) / (length(e1)-2)
    sigma2 = solve(t(xmat) %*% xmat) * var1
    t1     = bhead[2] / sqrt(sigma2[2,2])
    return(t1)
} # end func reg_tvalue
```

```{r}
gen_utagmat <- function(utagsvec, y) {
    if (is.null(utagsvec)){
        constant <- rep(1, length(y))
        mat <- as.matrix(constant)
        colnames(mat) <- "constant"
        return(mat)
    } # end if
    
    lst <- strsplit(utagsvec, split=",")
    
    tmp <- unlist(lst)
    tmp <- na.omit(tmp)
    
    threshold <- 5
    count <- table(tmp)
    count <- count[count >= threshold]
    count <- sort(count, decreasing = TRUE)
    
    setAll <- as.numeric(names(count))
    if (length(setAll) == 0){
        constant <- rep(1, length(y))
        mat <- as.matrix(constant)
        colnames(mat) <- "constant"
        return(mat)
    } # end if
    
    mat <- lapply(
        lst, 
        function(x){
            as.numeric(setAll %in% x)
        } # end lapply func
    ) # end lapply
    
    mat <- do.call(rbind, mat)
    colnames(mat) <- paste("user", setAll, sep="_")
    
    val <- apply(
        mat, 2, 
        function(x) {
            xmat = matrix(1, ncol=2, nrow=length(y))
            xmat[,2] = x
            bhead  = solve(t(xmat) %*% xmat, t(xmat) %*% y)
            yhead  = xmat %*% bhead
            e1     = y - yhead
            var1   = sum(e1 * e1) / (length(e1)-2)
            sigma2 = solve(t(xmat) %*% xmat) * var1
            t1     = bhead[2] / sqrt(sigma2[2,2])
            return(t1)
        } # end apply func
    ) # end apply
    
    val <- abs(val)
    val <- sort(val, decreasing = TRUE)
    val <- val[val >= 1]
    
    mat <- mat[,names(val)]
    mat <- cbind(1,mat)
    colnames(mat)[1] <- "constant"
    
    return(mat)
} # end func gen_utagmat
```

```{r}
umat1 = gen_utagmat(
    NULL,
    rtb1_train$paying_price)
head(umat1)
```


```{r}
umat1 = gen_utagmat(
    rtb1_train$user_tags,
    rtb1_train$paying_price)
head(umat1)
```

```{r}
y = rtb1_train$paying_price
w = solve(t(umat1) %*% umat1, t(umat1) %*% y)
print(w)
```

# Question 03
```{r}
load(file.path(filePathData, "rtb1_train.rdata"))
rtb1_train_tmp <- rtb1_train
```

```{r}
head(rtb1_train$user_agent)
```

```{r}
# define the input vector
utagstr=c("Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.12 (KHTML, like Gecko) Maxthon/3.0 Chrome/18.0.966.0 Safari/535.12", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1")

# define regular expression pattern 
pattern <- "([A-Za-z][A-Za-z0-9]{1,})" 

# do regular expression matching. 
list2=regmatches(utagstr, gregexpr(pattern, utagstr)) 

#keep only unique words in each row.
list2=lapply(list2, unique) 
print(list2)
```

```{r}
utagsvec <- rtb1_train$user_agent
y <- rtb1_train$paying_price
gen_uagentmat <- function(utagsvec, y) {
    if (is.null(utagsvec)){
        constant <- rep(1, length(y))
        mat <- as.matrix(constant)
        colnames(mat) <- "constant"
        return(mat)
    } # end if
    
    # define regular expression pattern 
    pattern <- "([A-Za-z][A-Za-z0-9]{1,})" 
    # do regular expression matching. 
    lst=regmatches(utagsvec, gregexpr(pattern, utagsvec)) 
    #keep only unique words in each row.
    lst=lapply(lst, unique)
    
    tmp <- unlist(lst)
    tmp <- na.omit(tmp)
    
    threshold1 <- 10
    threshold2 <- floor(0.5 * length(y))
    count <- table(tmp)
    idx1 <- count >= threshold1
    idx2 <- count <= threshold2
    count <- count[idx1 & idx2]
    count <- sort(count, decreasing = TRUE)
    
    setAll <- names(count)
    if (length(setAll) == 0){
        constant <- rep(1, length(y))
        mat <- as.matrix(constant)
        colnames(mat) <- "constant"
        return(mat)
    } # end if
    
    mat <- lapply(
        lst, 
        function(x){
            as.numeric(setAll %in% x)
        } # end lapply func
    ) # end lapply
    
    mat <- do.call(rbind, mat)
    colnames(mat) <- paste("agent", setAll, sep="_")
    
    val <- apply(
        mat, 2, 
        function(x) {
            xmat = matrix(1, ncol=2, nrow=length(y))
            xmat[,2] = x
            bhead  = solve(t(xmat) %*% xmat, t(xmat) %*% y)
            yhead  = xmat %*% bhead
            e1     = y - yhead
            var1   = sum(e1 * e1) / (length(e1)-2)
            sigma2 = solve(t(xmat) %*% xmat) * var1
            t1     = bhead[2] / sqrt(sigma2[2,2])
            return(t1)
        } # end apply func
    ) # end apply
    
    val <- abs(val)
    val <- val[sort(names(val), decreasing = TRUE)]
    val <- sort(val, decreasing = TRUE)
    val <- val[val >= 1]
    
    mat <- mat[,names(val)]
    mat <- cbind(1,mat)
    colnames(mat)[1] <- "constant"
    
    return(mat)
} # end func gen_utagmat
```

```{r}
rtb1_train = rtb1_train_tmp[1:1500,] 
y = rtb1_train$paying_price 
umat1 = gen_uagentmat(rtb1_train$user_agent,y) 
head(umat1)
```

```{r}
print(head(sort(colSums(umat1), decreasing = TRUE),n=10))
```

