---
title: "Untitled"
author: "Kuei Yueh Ko"
date: "2017年4月17日"
output: html_document
---

# 
```{r}
workdir <- "E:\\GoogleDrive\\Docs\\Course\\NTU\\105_02_StatLearn\\HW03"
setwd(workdir)
```

```{r}
load("phonetrain.rdata")
```

```{r}
pgm_train_innerFun <- function(dat){
    covMat <- cov(dat)
    logDet <- determinant(covMat)
    lst <- list()
    lst$mu1 = apply(dat, 2, mean)
    
    lst$sigma1 = covMat
    lst$prec1  = solve(covMat)
    lst$detsig_log = as.vector(
            logDet$sign * logDet$modulus)
    
    lst$N1 = nrow(dat)
    return(lst)
}

pgm_train <- function(itemName, datTrain){
    lst <- list()
    for(idx in itemName){
        lst[[idx]] <- pgm_train_innerFun(datTrain[[idx]])
    } # end for loop
    return(lst)
}
```

```{r}
train2 = list() 
for(aclass in outclass) { 
    train2[[aclass]] = traindata[[aclass]][1:500,] 
}
model1=pgm_train(outclass, train2) 
```

```{r}
model1[1]
```

```{r}
dat <- traindata[[1]][1:500,] 
head(dat)
apply(dat,2, mean)
cov(dat)
```

# question 1b
```{r}
myKernal <- function(x, lstModel){
    p <- length(x)
    x <- matrix(as.numeric(x), ncol=1)
    
    mu          <- matrix(lstModel$mu1, ncol=1)
    sigmaInv    <- lstModel$prec1
    sigmaDetlog <- lstModel$detsig_log
    
    valKernal <- -0.5 * t(x - mu) %*% sigmaInv %*% (x - mu)
    res <- as.numeric((-p/2) * sigmaDetlog + valKernal)
    return(res)
}

pgm_predict <- function(lstOfModel, dat){
    # 
    res <- apply(dat, 1, function(x){
        vec <- lapply(lstOfModel, function(lstModel){
            return(myKernal(x, lstModel))
        }) # end lapply
        
        idx <- order(
            unlist(vec), 
            decreasing = TRUE)[1]
        return(idx)
    }) # end apply
    
    # return
    names(res) <- NULL
    return(res)
}
```

```{r}
load('phonetrain.rdata') 
load('phonetest1.rdata') 
```

```{r}
dat <- testds1_feature
dat[1,]

myKernal(dat[1,], model1[[1]])


unlist(pgm_predict(model1, dat[1,]))

pgm_predict(model1, dat)[1:50]
```

