---
title: "Bootstrap"
author: "Kuei Yueh Ko"
date: "2017年3月9日"
output: html_document
---

# Read the Data
Below are the data points read in into R session, including two test scores 
- GPA  (y)
- LSAT (x)
```{r}
x <- c(576, 635, 558, 578, 666, 580, 555, 661, 651, 605, 653, 575, 545, 572, 594)
y <- c(3.39, 3.30, 2.81, 3.03, 3.44, 3.07, 3.00, 3.42, 3.36, 3.13, 3.12, 2.74, 2.76, 2.88, 2.96)
```

Visualize the original sample points
```{r}
plot(x, y, pch=20, xlab="LSAT", ylab="GPA")
```

# Perform Bootstrap Analysis
create helper function for corr-coef calculation in each bootstrapping
```{r}
CalCor <- function(id, x, y){
    xp <- x[id]
    yp <- y[id]
    p <- cor(xp, yp)
    return(p)
} # end func CalCor
```

perform bootstrap
```{r}
id <- seq_along(x)
corBstrap <- replicate(1000, CalCor(sample(id, replace=TRUE),x,y))
```

estimation parameters
```{r}
corOri <- cor(x, y)              # Sample Corr-Coef
corBstrap_MU <- mean(corBstrap)
corBstrap_SE <- sd(corBstrap)    # Standard Error
##################################
cat("Sample Correlation: ", corOri, "\n",
    "Mean of Boostrapped Correlation: ", corBstrap_MU, "\n",
    "SE   of Boostrapped Correlation: ", corBstrap_SE)
```

visualize the distribution of bootstrapped corr-coef
```{r}
corDiff <- corBstrap - corOri
corDiffSort <- sort(corDiff)
corDiff84 <- corDiffSort[840]
corDiff50 <- corDiffSort[500]
corDiff16 <- corDiffSort[160]
##################################
# plot the histogram
hist(corDiff, col="grey70", 
     breaks=seq(-0.8, 0.5, by=0.02),
     ylim=c(0,100),
     xlab="Difference of bootstrap correlation\nand the sample correlation",
     main="Distribution of bootstrapped corr-coef")

# adding histogram percentiles
abline(v=corDiff84, col="red")
abline(v=corDiff50, col="red")
abline(v=corDiff16, col="red")

# emphasize the axis for visualization
axis(side=1, lwd = 2, at = seq(-0.8, 0.5, by=0.1))
axis(side=2, lwd = 2)
```

Confidence Interval 95% [2.5% --- 97.5%.]
```{r}
corDiff97.5 <- corDiffSort[975]
corDiff25   <- corDiffSort[25]
#####################################
print(corDiff97.5)
print(corDiff25)
```

